#!/bin/bash
lynx -dump http://ec2-54-247-18-97.eu-west-1.compute.amazonaws.com/PREPROD/YAKREP/BATCH/DB2Ontology.php?zone=1 > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone1.log
cp /home/bitnami/stack/apache2/htdocs/PREPROD/YAKREP/BATCH/output/yakdicotitle_zone1.xml /home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotitle_zone1.xml
cp /home/bitnami/stack/apache2/htdocs/PREPROD/YAKREP/BATCH/output/yakdicotext_zone1.xml /home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotext_zone1.xml
/home/bitnami/stack/exalead/theindex/bin/cvadmin linguistic compile-ontology input="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotitle_zone1.xml" output="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/dico/yakdicotitle_zone1/" > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone1.log
/home/bitnami/stack/exalead/theindex/bin/cvadmin linguistic compile-ontology input="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotext_zone1.xml" output="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/dico/yakdicotext_zone1/" > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone1.log
lynx -dump http://ec2-54-247-18-97.eu-west-1.compute.amazonaws.com/PREPROD/YAKREP/BATCH/DB2Ontology.php?zone=2 > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone2.log
cp /home/bitnami/stack/apache2/htdocs/PREPROD/YAKREP/BATCH/output/yakdicotitle_zone2.xml /home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotitle_zone2.xml
cp /home/bitnami/stack/apache2/htdocs/PREPROD/YAKREP/BATCH/output/yakdicotext_zone2.xml /home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotext_zone2.xml
/home/bitnami/stack/exalead/theindex/bin/cvadmin linguistic compile-ontology input="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotitle_zone2.xml" output="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/dico/yakdicotitle_zone2/" > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone2.log
/home/bitnami/stack/exalead/theindex/bin/cvadmin linguistic compile-ontology input="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/ontologies/yakdicotext_zone2.xml" output="/home/bitnami/stack/exalead/cloudview-V6R2013.SP2.44163-linux-x64/resource/all-arch/yakwala/dico/yakdicotext_zone2/" > /home/bitnami/stack/apache2/htdocs/LOG/PREPROD/ontoBuilder_zone2.log